### ISSUE TITLE
Gracefully handle die being called more than once

### ISSUE THREAD

**Issue by mike-zorn** [troygoode/node-diehard#2]
If `diehard.die` somehow is called more than once the `handlers` array will call all the handlers a second time with the signal as an argument the `done` argument which will throw when the callback is called in the handler itself.

**Comment by troygoode** [comment]
@apechimp What _should_ we do here? (Obviously not what it currently does.) Is it better to only process the handlers array once (deregister a handler once we call it), or to just fix it so we're calling it with the correct arguments each time?

**Comment by mike-zorn** [comment]
I think only process the handlers once. The normal use case for these handlers is to close connections. If you try to close an already closed connection, most things throw exceptions.
